Run the service with curl (in a separate terminal window), by running the following
command:

$ curl localhost:8080/


If you use Gradle, add the following dependency to your `build.gradle` file:

include::complete/build.gradle[tag=tests]


If you use Maven, add the following to your `pom.xml` file:

include::complete/pom.xml[tag=tests]

If you use Gradle, run the following command in a terminal
window (in the `complete` directory):

./gradlew bootRun


If you use Maven, run the following command in a terminal window (in the `complete`
directory):

./mvnw spring-boot:run




If you are building a web site for your business, you probably need to add some management
services. Spring Boot provides several such services (such as health, audits, beans, and
more) with its
http://docs.spring.io/spring-boot/docs/{spring_boot_version}/reference/htmlsingle/#production-ready[actuator module].

If you use Gradle, add the following dependency to your `build.gradle` file:

[source,groovy,indent=0]
----
include::complete/build.gradle[tag=actuator]
----

If you use Maven, add the following dependency to your `pom.xml` file:

[source,xml,indent=0]
----
include::complete/pom.xml[tag=actuator]
----

Then restart the application. 

You should see that a new set of RESTful end points have been added to the application.
These are management services provided by Spring Boot. The following listing shows typical
output:


The actuator exposes the following:

* errors
* http://localhost:8080/actuator/health[actuator/health]
* http://localhost:8080/actuator/info[actuator/info]
* http://localhost:8080/actuator[actuator]

NOTE: There is also an `/actuator/shutdown` endpoint, but, by default, it is visible only
through JMX. To http://docs.spring.io/spring-boot/docs/{spring_boot_version}/reference/htmlsingle/#production-ready-endpoints-enabling-endpoints[enable it as an HTTP endpoint], add
`management.endpoints.web.exposure.include=health,info,shutdown` to your `application.properties` file.
However, you probably should not enable the shutdown endpoint for a publicly available
application.

You can check the health of the application by running the following command:

====
[source,bash]
----
$ curl localhost:8080/actuator/health
{"status":"UP"}
----
====

You can try also to invoke shutdown through curl, to see what happens when you have not
added the necessary line (shown in the preceding note) to `application.properties`:

====
[source,bash]
----
$ curl -X POST localhost:8080/actuator/shutdown
{"timestamp":1401820343710,"error":"Method Not Allowed","status":405,"message":"Request method 'POST' not supported"}
----
====


